package com.donaldduckith.expandedflowers.datagen;

import com.donaldduckith.expandedflowers.ExpandedFlowers;
import com.donaldduckith.expandedflowers.registry.ModBlocks;
import com.donaldduckith.expandedflowers.registry.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends BlockTagsProvider {
    public ModBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(output, lookupProvider, ExpandedFlowers.MODID);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tag(BlockTags.FLOWERS)
                .add(ModBlocks.WHITE_AGAPANTHUS.get())
                .add(ModBlocks.WHITE_ARCTOTIS.get())
                .add(ModBlocks.WHITE_BABIANA.get())
                .add(ModBlocks.WHITE_BIRD_OF_PARADISE.get())
                .add(ModBlocks.WHITE_BOTTLEBRUSH.get())
                .add(ModBlocks.WHITE_BOTTLEBRUSH_END.get())
                .add(ModBlocks.WHITE_CHRYSANTHEMUM.get())
                .add(ModBlocks.WHITE_CLEMATIS.get())
                .add(ModBlocks.WHITE_FIRE_LILY.get())
                .add(ModBlocks.WHITE_FOXGLOVE.get())
                .add(ModBlocks.WHITE_GREVILLEA.get())
                .add(ModBlocks.WHITE_HELLEBORE.get())
                .add(ModBlocks.WHITE_HOLLYHOCK.get())
                .add(ModBlocks.WHITE_HYDRANGEA.get())
                .add(ModBlocks.WHITE_LILAC.get())
                .add(ModBlocks.WHITE_ORCHID.get())
                .add(ModBlocks.WHITE_PANSY.get())
                .add(ModBlocks.WHITE_PEONY.get())
                .add(ModBlocks.WHITE_POPPY.get())
                .add(ModBlocks.WHITE_ROSE_BUSH.get())
                .add(ModBlocks.WHITE_ROSEMARY.get())
                .add(ModBlocks.WHITE_WARATAH.get())
                .add(ModBlocks.WHITE_WATTLE_VINE.get())

                .add(ModBlocks.LIGHT_GRAY_GREVILLEA.get())
                .add(ModBlocks.LIGHT_GRAY_ROSE_BUSH.get())

                .add(ModBlocks.GRAY_AGAPANTHUS.get())
                .add(ModBlocks.GRAY_GREVILLEA.get())

                .add(ModBlocks.BLACK_PANSY.get())
                .add(ModBlocks.BLACK_HOLLYHOCK.get())
                .add(ModBlocks.BLACK_CHRYSANTHEMUM.get())
                .add(ModBlocks.BLACK_GREVILLEA.get())
                .add(ModBlocks.BLACK_HELLEBORE.get())
                .add(ModBlocks.BLACK_TULIP.get())
                .add(ModBlocks.BLACK_ROSE_BUSH.get())

                .add(ModBlocks.BROWN_PANSY.get())

                .add(ModBlocks.RED_ARCTOTIS.get())
                .add(ModBlocks.RED_BOTTLEBRUSH.get())
                .add(ModBlocks.RED_BOTTLEBRUSH_END.get())
                .add(ModBlocks.RED_CHRYSANTHEMUM.get())
                .add(ModBlocks.RED_CLEMATIS.get())
                .add(ModBlocks.RED_FIRE_LILY.get())
                .add(ModBlocks.RED_GREVILLEA.get())
                .add(ModBlocks.RED_HELLEBORE.get())
                .add(ModBlocks.RED_HOLLYHOCK.get())
                .add(ModBlocks.RED_HYDRANGEA.get())
                .add(ModBlocks.RED_PANSY.get())
                .add(ModBlocks.RED_WARATAH.get())
                .add(ModBlocks.RED_WATTLE_VINE.get())

                .add(ModBlocks.ORANGE_AGAPANTHUS.get())
                .add(ModBlocks.ORANGE_ARCTOTIS.get())
                .add(ModBlocks.ORANGE_BIRD_OF_PARADISE.get())
                .add(ModBlocks.ORANGE_BOTTLEBRUSH.get())
                .add(ModBlocks.ORANGE_BOTTLEBRUSH_END.get())
                .add(ModBlocks.ORANGE_CHRYSANTHEMUM.get())
                .add(ModBlocks.ORANGE_FIRE_LILY.get())
                .add(ModBlocks.ORANGE_GREVILLEA.get())
                .add(ModBlocks.ORANGE_ORCHID.get())
                .add(ModBlocks.ORANGE_PANSY.get())
                .add(ModBlocks.ORANGE_POPPY.get())
                .add(ModBlocks.ORANGE_ROSE_BUSH.get())
                .add(ModBlocks.ORANGE_WATTLE_VINE.get())

                .add(ModBlocks.YELLOW_ARCTOTIS.get())
                .add(ModBlocks.YELLOW_BIRD_OF_PARADISE.get())
                .add(ModBlocks.YELLOW_BOTTLEBRUSH.get())
                .add(ModBlocks.YELLOW_BOTTLEBRUSH_END.get())
                .add(ModBlocks.YELLOW_CLEMATIS.get())
                .add(ModBlocks.YELLOW_CHRYSANTHEMUM.get())
                .add(ModBlocks.YELLOW_FIRE_LILY.get())
                .add(ModBlocks.YELLOW_FOXGLOVE.get())
                .add(ModBlocks.YELLOW_GREVILLEA.get())
                .add(ModBlocks.YELLOW_HELLEBORE.get())
                .add(ModBlocks.YELLOW_HOLLYHOCK.get())
                .add(ModBlocks.YELLOW_HYDRANGEA.get())
                .add(ModBlocks.YELLOW_ORCHID.get())
                .add(ModBlocks.YELLOW_PANSY.get())
                .add(ModBlocks.YELLOW_POPPY.get())
                .add(ModBlocks.YELLOW_ROSE_BUSH.get())
                .add(ModBlocks.YELLOW_TULIP.get())
                .add(ModBlocks.YELLOW_WARATAH.get())
                .add(ModBlocks.YELLOW_WATTLE_VINE.get())

                .add(ModBlocks.LIME_CHRYSANTHEMUM.get())
                .add(ModBlocks.LIME_HELLEBORE.get())
                .add(ModBlocks.LIME_HYDRANGEA.get())
                .add(ModBlocks.LIME_ROSE_BUSH.get())

                .add(ModBlocks.GREEN_CHRYSANTHEMUM.get())

                .add(ModBlocks.CYAN_ORCHID.get())
                .add(ModBlocks.CYAN_OXEYE_DAISY.get())

                .add(ModBlocks.LIGHT_BLUE_AZURE_BLUET.get())
                .add(ModBlocks.LIGHT_BLUE_CHRYSANTHEMUM.get())
                .add(ModBlocks.LIGHT_BLUE_HYDRANGEA.get())

                .add(ModBlocks.BLUE_AGAPANTHUS.get())
                .add(ModBlocks.BLUE_CHRYSANTHEMUM.get())
                .add(ModBlocks.BLUE_CLEMATIS.get())
                .add(ModBlocks.BLUE_FOXGLOVE.get())
                .add(ModBlocks.BLUE_HYDRANGEA.get())
                .add(ModBlocks.BLUE_PANSY.get())
                .add(ModBlocks.BLUE_ROSE_BUSH.get())

                .add(ModBlocks.PURPLE_AGAPANTHUS.get())
                .add(ModBlocks.PURPLE_BABIANA.get())
                .add(ModBlocks.PURPLE_CHRYSANTHEMUM.get())
                .add(ModBlocks.PURPLE_CLEMATIS.get())
                .add(ModBlocks.PURPLE_FIRE_LILY.get())
                .add(ModBlocks.PURPLE_FOXGLOVE.get())
                .add(ModBlocks.PURPLE_HELLEBORE.get())
                .add(ModBlocks.PURPLE_HYDRANGEA.get())
                .add(ModBlocks.PURPLE_LILAC.get())
                .add(ModBlocks.PURPLE_ORCHID.get())
                .add(ModBlocks.PURPLE_PANSY.get())
                .add(ModBlocks.PURPLE_ROSE_BUSH.get())
                .add(ModBlocks.PURPLE_ROSEMARY.get())
                .add(ModBlocks.PURPLE_TULIP.get())

                .add(ModBlocks.MAGENTA_AGAPANTHUS.get())
                .add(ModBlocks.MAGENTA_ARCTOTIS.get())
                .add(ModBlocks.MAGENTA_BABIANA.get())
                .add(ModBlocks.MAGENTA_BIRD_OF_PARADISE.get())
                .add(ModBlocks.MAGENTA_BOTTLEBRUSH.get())
                .add(ModBlocks.MAGENTA_BOTTLEBRUSH_END.get())
                .add(ModBlocks.MAGENTA_CHRYSANTHEMUM.get())
                .add(ModBlocks.MAGENTA_CLEMATIS.get())
                .add(ModBlocks.MAGENTA_FIRE_LILY.get())
                .add(ModBlocks.MAGENTA_FOXGLOVE.get())
                .add(ModBlocks.MAGENTA_GREVILLEA.get())
                .add(ModBlocks.MAGENTA_HELLEBORE.get())
                .add(ModBlocks.MAGENTA_HOLLYHOCK.get())
                .add(ModBlocks.MAGENTA_HYDRANGEA.get())
                .add(ModBlocks.MAGENTA_ORCHID.get())
                .add(ModBlocks.MAGENTA_PANSY.get())
                .add(ModBlocks.MAGENTA_PEONY.get())
                .add(ModBlocks.MAGENTA_ROSE_BUSH.get())
                .add(ModBlocks.MAGENTA_TULIP.get())
                .add(ModBlocks.MAGENTA_WARATAH.get())

                .add(ModBlocks.PINK_AGAPANTHUS.get())
                .add(ModBlocks.PINK_ARCTOTIS.get())
                .add(ModBlocks.PINK_BABIANA.get())
                .add(ModBlocks.PINK_BOTTLEBRUSH.get())
                .add(ModBlocks.PINK_BOTTLEBRUSH_END.get())
                .add(ModBlocks.PINK_CHRYSANTHEMUM.get())
                .add(ModBlocks.PINK_CLEMATIS.get())
                .add(ModBlocks.PINK_FIRE_LILY.get())
                .add(ModBlocks.PINK_FOXGLOVE.get())
                .add(ModBlocks.PINK_HELLEBORE.get())
                .add(ModBlocks.PINK_HOLLYHOCK.get())
                .add(ModBlocks.PINK_HYDRANGEA.get())
                .add(ModBlocks.PINK_LILAC.get())
                .add(ModBlocks.PINK_ORCHID.get())
                .add(ModBlocks.PINK_PANSY.get())
                .add(ModBlocks.PINK_ROSE_BUSH.get())
                .add(ModBlocks.PINK_ROSEMARY.get())
                .add(ModBlocks.PINK_WARATAH.get());

        tag(BlockTags.LEAVES)
                .add(ModBlocks.WHITE_BOUGAINVILLEA.get())
                .add(ModBlocks.RED_BOUGAINVILLEA.get())
                .add(ModBlocks.ORANGE_BOUGAINVILLEA.get())
                .add(ModBlocks.YELLOW_BOUGAINVILLEA.get())
                .add(ModBlocks.PURPLE_BOUGAINVILLEA.get())
                .add(ModBlocks.MAGENTA_BOUGAINVILLEA.get())
                .add(ModBlocks.PINK_BOUGAINVILLEA.get())
                .add(ModBlocks.WHITE_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.RED_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.ORANGE_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.YELLOW_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.MAGENTA_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.PINK_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.WHITE_WATTLE_LEAVES.get())
                .add(ModBlocks.RED_WATTLE_LEAVES.get())
                .add(ModBlocks.ORANGE_WATTLE_LEAVES.get())
                .add(ModBlocks.YELLOW_WATTLE_LEAVES.get());

        tag(BlockTags.CLIMBABLE)
                .add(ModBlocks.WHITE_WATTLE_VINE.get())
                .add(ModBlocks.RED_WATTLE_VINE.get())
                .add(ModBlocks.ORANGE_WATTLE_VINE.get())
                .add(ModBlocks.YELLOW_WATTLE_VINE.get())
                .add(ModBlocks.WHITE_BOTTLEBRUSH.get())
                .add(ModBlocks.WHITE_BOTTLEBRUSH_END.get())
                .add(ModBlocks.RED_BOTTLEBRUSH.get())
                .add(ModBlocks.RED_BOTTLEBRUSH_END.get())
                .add(ModBlocks.ORANGE_BOTTLEBRUSH.get())
                .add(ModBlocks.ORANGE_BOTTLEBRUSH_END.get())
                .add(ModBlocks.YELLOW_BOTTLEBRUSH.get())
                .add(ModBlocks.YELLOW_BOTTLEBRUSH_END.get())
                .add(ModBlocks.MAGENTA_BOTTLEBRUSH.get())
                .add(ModBlocks.MAGENTA_BOTTLEBRUSH_END.get())
                .add(ModBlocks.PINK_BOTTLEBRUSH.get())
                .add(ModBlocks.PINK_BOTTLEBRUSH_END.get())
                .add(ModBlocks.CLEMATIS_VINE.get())
                .add(ModBlocks.WHITE_CLEMATIS.get())
                .add(ModBlocks.RED_CLEMATIS.get())
                .add(ModBlocks.YELLOW_CLEMATIS.get())
                .add(ModBlocks.BLUE_CLEMATIS.get())
                .add(ModBlocks.PURPLE_CLEMATIS.get())
                .add(ModBlocks.MAGENTA_CLEMATIS.get())
                .add(ModBlocks.PINK_CLEMATIS.get());

        tag(BlockTags.SAPLINGS)
                .add(ModBlocks.WHITE_BOTTLEBRUSH_SAPLING.get())
                .add(ModBlocks.RED_BOTTLEBRUSH_SAPLING.get())
                .add(ModBlocks.ORANGE_BOTTLEBRUSH_SAPLING.get())
                .add(ModBlocks.YELLOW_BOTTLEBRUSH_SAPLING.get())
                .add(ModBlocks.MAGENTA_BOTTLEBRUSH_SAPLING.get())
                .add(ModBlocks.PINK_BOTTLEBRUSH_SAPLING.get())
                .add(ModBlocks.WHITE_BOUGAINVILLEA_SAPLING.get())
                .add(ModBlocks.RED_BOUGAINVILLEA_SAPLING.get())
                .add(ModBlocks.ORANGE_BOUGAINVILLEA_SAPLING.get())
                .add(ModBlocks.YELLOW_BOUGAINVILLEA_SAPLING.get())
                .add(ModBlocks.PURPLE_BOUGAINVILLEA_SAPLING.get())
                .add(ModBlocks.MAGENTA_BOUGAINVILLEA_SAPLING.get())
                .add(ModBlocks.PINK_BOUGAINVILLEA_SAPLING.get())
                .add(ModBlocks.WHITE_WATTLE_SAPLING.get())
                .add(ModBlocks.RED_WATTLE_SAPLING.get())
                .add(ModBlocks.ORANGE_WATTLE_SAPLING.get())
                .add(ModBlocks.YELLOW_WATTLE_SAPLING.get());

        tag(ModTags.Blocks.FLOWERING_LEAVES)
                .add(ModBlocks.WHITE_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.RED_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.ORANGE_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.YELLOW_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.MAGENTA_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.PINK_BOTTLEBRUSH_LEAVES.get())
                .add(ModBlocks.WHITE_BOUGAINVILLEA.get())
                .add(ModBlocks.RED_BOUGAINVILLEA.get())
                .add(ModBlocks.ORANGE_BOUGAINVILLEA.get())
                .add(ModBlocks.YELLOW_BOUGAINVILLEA.get())
                .add(ModBlocks.PURPLE_BOUGAINVILLEA.get())
                .add(ModBlocks.MAGENTA_BOUGAINVILLEA.get())
                .add(ModBlocks.PINK_BOUGAINVILLEA.get());

        tag(ModTags.Blocks.AZURE_BLUETS)
                .add(Blocks.AZURE_BLUET)
                .add(ModBlocks.LIGHT_BLUE_AZURE_BLUET.get());

        tag(ModTags.Blocks.LILACS)
                .add(Blocks.LILAC)
                .add(ModBlocks.WHITE_LILAC.get())
                .add(ModBlocks.PURPLE_LILAC.get())
                .add(ModBlocks.PINK_LILAC.get());

        tag(ModTags.Blocks.ORCHIDS)
                .add(Blocks.BLUE_ORCHID)
                .add(ModBlocks.WHITE_ORCHID.get())
                .add(ModBlocks.ORANGE_ORCHID.get())
                .add(ModBlocks.YELLOW_ORCHID.get())
                .add(ModBlocks.CYAN_ORCHID.get())
                .add(ModBlocks.PURPLE_ORCHID.get())
                .add(ModBlocks.MAGENTA_ORCHID.get())
                .add(ModBlocks.PINK_ORCHID.get());

        tag(ModTags.Blocks.OXEYE_DAISIES)
                .add(Blocks.OXEYE_DAISY)
                .add(ModBlocks.CYAN_OXEYE_DAISY.get());

        tag(ModTags.Blocks.PEONIES)
                .add(Blocks.PEONY)
                .add(ModBlocks.WHITE_PEONY.get())
                .add(ModBlocks.MAGENTA_PEONY.get());

        tag(ModTags.Blocks.POPPIES)
                .add(Blocks.POPPY)
                .add(ModBlocks.WHITE_POPPY.get())
                .add(ModBlocks.ORANGE_POPPY.get())
                .add(ModBlocks.YELLOW_POPPY.get());

        tag(ModTags.Blocks.ROSE_BUSHES)
                .add(Blocks.ROSE_BUSH)
                .add(ModBlocks.WHITE_ROSE_BUSH.get())
                .add(ModBlocks.LIGHT_GRAY_ROSE_BUSH.get())
                .add(ModBlocks.BLACK_ROSE_BUSH.get())
                .add(ModBlocks.ORANGE_ROSE_BUSH.get())
                .add(ModBlocks.YELLOW_ROSE_BUSH.get())
                .add(ModBlocks.LIME_ROSE_BUSH.get())
                .add(ModBlocks.BLUE_ROSE_BUSH.get())
                .add(ModBlocks.PURPLE_ROSE_BUSH.get())
                .add(ModBlocks.MAGENTA_ROSE_BUSH.get())
                .add(ModBlocks.PINK_ROSE_BUSH.get());

        tag(ModTags.Blocks.TULIPS)
                .add(Blocks.WHITE_TULIP)
                .add(ModBlocks.BLACK_TULIP.get())
                .add(Blocks.RED_TULIP)
                .add(Blocks.ORANGE_TULIP)
                .add(ModBlocks.YELLOW_TULIP.get())
                .add(ModBlocks.PURPLE_TULIP.get())
                .add(ModBlocks.MAGENTA_TULIP.get())
                .add(Blocks.PINK_TULIP);

        tag(ModTags.Blocks.CONVERTIBLE_PLANTS)
                .add(Blocks.ACACIA_SAPLING)
                .add(Blocks.ALLIUM)
                .add(Blocks.AZALEA)
                .add(Blocks.AZURE_BLUET)
                .add(Blocks.BUSH)
                .add(Blocks.BLUE_ORCHID)
                .add(Blocks.LILY_OF_THE_VALLEY)
                .add(Blocks.PINK_PETALS)
                .add(Blocks.ORANGE_TULIP)
                .add(Blocks.OXEYE_DAISY)
                .add(Blocks.ROSE_BUSH)
                .add(Blocks.VINE)
                .add(Blocks.WILDFLOWERS)
                .add(ModBlocks.RED_BOTTLEBRUSH_SAPLING.get())
                .add(ModBlocks.MAGENTA_BOUGAINVILLEA_SAPLING.get())
                .add(ModBlocks.YELLOW_WATTLE_SAPLING.get())
                .add(ModBlocks.PURPLE_CLEMATIS.get())
                .add(ModBlocks.PINK_LILAC.get())
                .add(ModBlocks.PURPLE_AGAPANTHUS.get())
                .add(ModBlocks.LIGHT_BLUE_AZURE_BLUET.get())
                .add(ModBlocks.PINK_PANSY.get())
                .add(ModBlocks.YELLOW_PANSY.get())
                .add(ModBlocks.RED_GREVILLEA.get())
                .add(ModBlocks.RED_WARATAH.get())
                .add(ModBlocks.PURPLE_ROSEMARY.get())
                .add(ModBlocks.PINK_FOXGLOVE.get())
                .add(ModBlocks.ORANGE_BIRD_OF_PARADISE.get())
                .add(ModBlocks.YELLOW_ARCTOTIS.get())
                .add(ModBlocks.MAGENTA_BABIANA.get());
    }

}
